version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: parthos-postgres
    environment:
      POSTGRES_DB: parthosdb
      POSTGRES_USER: parthosadmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongpassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parthosadmin -d parthosdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: parthos-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://parthosadmin:strongpassword123@postgres:5432/parthosdb

      # Other environment variables remain the same
      - NEXTAUTH_SECRET=your_secret_here
      - JWT_SECRET=your_jwt_secret
      - NEXTAUTH_URL=http://localhost:3000

    volumes:
      - node_modules:/app/node_modules
      - .next:/app/.next

volumes:
  postgres_data:
  node_modules:

networks:
  default:
    name: parthos-network